
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async startStream(onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_stream", { onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTaskCount() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async spawnProcess(cmd: string, args: string[], cwd: string, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_process", { cmd, args, cwd, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelProcess(taskId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_process", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseProcess(taskId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_process", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeProcess(taskId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_process", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn a Claude Code subprocess in headless streaming mode.
 * 
 * Retrieves the API key from the macOS Keychain, builds the Claude CLI command,
 * and spawns it through the process manager with secure env var injection.
 * The prompt is expected to be already optimized by the prompt engine (dispatch_task handles this).
 * 
 * Returns the task_id for tracking the process.
 */
async spawnClaudeTask(prompt: string, projectDir: string, taskId: string | null, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_claude_task", { prompt, projectDir, taskId, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Store a Claude API key in the macOS Keychain.
 * 
 * Validates that the key starts with "sk-ant-" before storing.
 * SECURITY: The key is never logged or included in error messages.
 */
async setClaudeApiKey(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_claude_api_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether a Claude API key is stored in the macOS Keychain.
 */
async hasClaudeApiKey() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_claude_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate a Claude Code result JSON for silent failures.
 * 
 * Parses the result JSON line with `parse_stream_line`, then validates via
 * `validate_result` — checking is_error, empty result, zero turns, and status.
 */
async validateClaudeResult(resultJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_claude_result", { resultJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the stored Claude API key from the macOS Keychain.
 */
async deleteClaudeApiKey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_claude_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record a task completion event with file changes.
 */
async recordTaskCompletionCmd(taskId: string, toolName: string, eventType: string, prompt: string | null, summary: string | null, projectDir: string, durationMs: number | null, costUsd: number | null, filesJson: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_task_completion_cmd", { taskId, toolName, eventType, prompt, summary, projectDir, durationMs, costUsd, filesJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get recent file changes for a project.
 */
async getRecentChanges(projectDir: string, limit: number) : Promise<Result<FileChangeRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recent_changes", { projectDir, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a summary of recent context events with their file paths.
 */
async getContextSummary(projectDir: string, limit: number) : Promise<Result<ContextEventWithFiles[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_context_summary", { projectDir, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create an isolated git worktree for a task.
 * 
 * Creates a new branch and worktree directory in a sibling `.whalecode-worktrees/` folder.
 * Returns the WorktreeEntry for frontend tracking.
 */
async createWorktree(taskId: string, projectDir: string) : Promise<Result<WorktreeEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_worktree", { taskId, projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check for file-level conflicts between two worktree branches.
 * 
 * Auto-commits any uncommitted changes in both worktrees before running
 * the three-way merge conflict detection.
 */
async checkWorktreeConflicts(projectDir: string, branchA: string, branchB: string) : Promise<Result<ConflictReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_worktree_conflicts", { projectDir, branchA, branchB }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate per-file unified diffs between a worktree branch and the default branch.
 * 
 * Auto-commits any uncommitted changes in the worktree before generating diffs
 * to capture all tool changes.
 */
async getWorktreeDiff(projectDir: string, branchName: string) : Promise<Result<WorktreeDiffReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_worktree_diff", { projectDir, branchName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Merge a worktree branch into the main/default branch.
 * 
 * SAFE-04: Pre-merge conflict gate — checks for conflicts against the default branch
 * and all other active whalecode branches before merging. If any conflicts are detected,
 * the merge is blocked and an error is returned.
 */
async mergeWorktree(projectDir: string, branchName: string, acceptedFiles: string[] | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_worktree", { projectDir, branchName, acceptedFiles }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clean up stale/invalid worktrees from previous crashed sessions.
 * 
 * Returns the names of worktrees that were cleaned up.
 */
async cleanupWorktrees(projectDir: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_worktrees", { projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all active whalecode worktrees for the project.
 */
async listWorktrees(projectDir: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_worktrees", { projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn a Gemini CLI subprocess in headless streaming mode.
 * 
 * Retrieves the API key from the macOS Keychain, builds the Gemini CLI command,
 * and spawns it through the process manager with secure env var injection.
 * The prompt is expected to be already optimized by the prompt engine (dispatch_task handles this).
 * 
 * Returns the task_id for tracking the process.
 */
async spawnGeminiTask(prompt: string, projectDir: string, taskId: string | null, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_gemini_task", { prompt, projectDir, taskId, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Store a Gemini API key in the macOS Keychain.
 * 
 * Validates that the key is non-empty and has reasonable length (> 10 chars).
 * NOTE: Gemini API keys have no known prefix pattern (unlike Claude's sk-ant-).
 * SECURITY: The key is never logged or included in error messages.
 */
async setGeminiApiKey(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_gemini_api_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether a Gemini API key is stored in the macOS Keychain.
 */
async hasGeminiApiKey() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_gemini_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate a Gemini CLI result JSON for silent failures.
 * 
 * Parses the result JSON line with `parse_stream_line`, then validates via
 * `validate_result` — checking empty response, error status, and error events.
 */
async validateGeminiResult(resultJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_gemini_result", { resultJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the stored Gemini API key from the macOS Keychain.
 */
async deleteGeminiApiKey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_gemini_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn a Codex CLI subprocess in headless streaming mode.
 * 
 * Retrieves the API key from the macOS Keychain, builds the Codex CLI command,
 * and spawns it through the process manager with secure env var injection.
 * The prompt is expected to be already optimized by the prompt engine (dispatch_task handles this).
 * 
 * Returns the task_id for tracking the process.
 */
async spawnCodexTask(prompt: string, projectDir: string, taskId: string | null, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_codex_task", { prompt, projectDir, taskId, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Store a Codex (OpenAI) API key in the macOS Keychain.
 * 
 * Validates that the key starts with "sk-" (OpenAI key format) and is non-empty.
 * SECURITY: The key is never logged or included in error messages.
 */
async setCodexApiKey(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_codex_api_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether a Codex (OpenAI) API key is stored in the macOS Keychain.
 */
async hasCodexApiKey() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_codex_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate a Codex CLI result JSON for silent failures.
 * 
 * Parses the result JSON line with `parse_stream_line`, then validates via
 * `validate_result` — checking empty response, error status, and error events.
 */
async validateCodexResult(resultJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_codex_result", { resultJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the stored Codex (OpenAI) API key from the macOS Keychain.
 */
async deleteCodexApiKey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_codex_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Suggest the best tool for a given prompt based on keyword heuristics and tool availability.
 * 
 * Checks which tools currently have running processes to determine busyness,
 * then delegates to TaskRouter::suggest for the routing decision.
 */
async suggestTool(prompt: string) : Promise<Result<RoutingSuggestion, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suggest_tool", { prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dispatch a task to the specified tool (claude or gemini).
 * 
 * Enforces max 1 running process per tool. Routes to the correct spawn function
 * based on tool_name, then updates the ProcessEntry with tool metadata.
 */
async dispatchTask(prompt: string, projectDir: string, toolName: string, taskId: string | null, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_task", { prompt, projectDir, toolName, taskId, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dispatch an orchestrated multi-agent task using two-phase orchestration.
 * 
 * Phase 1 (Decompose): Master agent analyzes task, returns JSON sub-task assignments.
 * Phase 2 (Execute): Each sub-task dispatched to assigned agent in parallel.
 * Phase 3 (Review): Master agent reviews all worker results and provides summary.
 */
async dispatchOrchestratedTask(prompt: string, projectDir: string, config: OrchestratorConfig, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<OrchestrationPlan, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_orchestrated_task", { prompt, projectDir, config, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get context/token usage information for agents involved in a task.
 */
async getAgentContextInfo(taskId: string) : Promise<Result<AgentContextInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent_context_info", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Preview optimized prompts for all supported tools without dispatching.
 * 
 * Returns a Vec<OptimizedPrompt> showing how the prompt would be transformed
 * for each tool (claude, gemini). Used by frontend for prompt preview UI.
 */
async optimizePrompt(prompt: string, projectDir: string) : Promise<Result<OptimizedPrompt[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("optimize_prompt", { prompt, projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send text to a running process's stdin.
 */
async sendToProcess(taskId: string, text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_to_process", { taskId, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove completed/failed processes older than 5 minutes from state.
 */
async cleanupCompletedProcesses() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_completed_processes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentConfig = { tool_name: string; sub_agent_count: number; is_master: boolean }
export type AgentContextInfo = { tool_name: string; input_tokens: number | null; output_tokens: number | null; total_tokens: number | null; cost_usd: number | null; status: string }
export type ConflictFile = { path: string }
export type ConflictReport = { has_conflicts: boolean; conflicting_files: ConflictFile[]; worktree_a: string; worktree_b: string }
/**
 * A context event with its associated file paths, suitable for IPC return.
 */
export type ContextEventWithFiles = { id: number; task_id: string; tool_name: string; event_type: string; prompt: string | null; summary: string | null; project_dir: string; metadata: string | null; duration_ms: number | null; cost_usd: number | null; created_at: string; files: string[] }
export type DecompositionResult = { tasks: SubTaskDef[] }
export type FileChangeRecord = { file_path: string; change_type: string; tool_name: string; summary: string | null; created_at: string }
export type FileDiff = { path: string; status: string; old_path: string | null; patch: string; additions: number; deletions: number }
/**
 * An optimized prompt for a specific tool, ready for IPC export.
 */
export type OptimizedPrompt = { tool_name: string; original_prompt: string; optimized_prompt: string }
export type OrchestrationPhase = "Decomposing" | "Executing" | "Reviewing" | "Completed" | "Failed"
export type OrchestrationPlan = { task_id: string; original_prompt: string; sub_tasks: SubTask[]; master_agent: string; phase: OrchestrationPhase; decomposition: DecompositionResult | null; worker_results: WorkerResult[] }
export type OrchestratorConfig = { agents: AgentConfig[]; master_agent: string }
export type OutputEvent = { event: "stdout"; data: string } | { event: "stderr"; data: string } | { event: "exit"; data: number } | { event: "error"; data: string }
export type RoutingSuggestion = { suggested_tool: string; confidence: number; reason: string; alternative_tool: string | null; tool_available: boolean }
export type SubTask = { id: string; prompt: string; assigned_agent: string; status: string; parent_task_id: string }
export type SubTaskDef = { agent: string; prompt: string; description: string }
export type TAURI_CHANNEL<TSend> = null
export type WorkerResult = { task_id: string; agent: string; exit_code: number; output_summary: string }
export type WorktreeDiffReport = { branch_name: string; default_branch: string; files: FileDiff[]; total_additions: number; total_deletions: number }
export type WorktreeEntry = { task_id: string; worktree_name: string; branch_name: string; path: string; 
/**
 * ISO 8601 timestamp string (specta does not implement Type for chrono::DateTime)
 */
created_at: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
