
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async startStream(onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_stream", { onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTaskCount() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async spawnProcess(cmd: string, args: string[], cwd: string, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_process", { cmd, args, cwd, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelProcess(taskId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_process", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseProcess(taskId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_process", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeProcess(taskId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_process", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn a Claude Code subprocess in headless streaming mode.
 * 
 * Retrieves the API key from the macOS Keychain, builds the Claude CLI command,
 * and spawns it through the process manager with secure env var injection.
 * 
 * Returns the task_id for tracking the process.
 */
async spawnClaudeTask(prompt: string, projectDir: string, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_claude_task", { prompt, projectDir, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Store a Claude API key in the macOS Keychain.
 * 
 * Validates that the key starts with "sk-ant-" before storing.
 * SECURITY: The key is never logged or included in error messages.
 */
async setClaudeApiKey(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_claude_api_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether a Claude API key is stored in the macOS Keychain.
 */
async hasClaudeApiKey() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_claude_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate a Claude Code result JSON for silent failures.
 *
 * Parses the result JSON line with `parse_stream_line`, then validates via
 * `validate_result` — checking is_error, empty result, zero turns, and status.
 */
async validateClaudeResult(resultJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_claude_result", { resultJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the stored Claude API key from the macOS Keychain.
 */
async deleteClaudeApiKey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_claude_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create an isolated git worktree for a task.
 */
async createWorktree(taskId: string, projectDir: string) : Promise<Result<WorktreeEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_worktree", { taskId, projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check for file-level conflicts between two worktree branches.
 */
async checkWorktreeConflicts(projectDir: string, branchA: string, branchB: string) : Promise<Result<ConflictReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_worktree_conflicts", { projectDir, branchA, branchB }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Merge a worktree branch into the main/default branch.
 * SAFE-04: Pre-merge conflict gate.
 */
async mergeWorktree(projectDir: string, branchName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_worktree", { projectDir, branchName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clean up stale/invalid worktrees from previous crashed sessions.
 */
async cleanupWorktrees(projectDir: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_worktrees", { projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all active whalecode worktrees for the project.
 */
async listWorktrees(projectDir: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_worktrees", { projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Suggest the best tool for a given prompt based on keyword heuristics and tool availability.
 */
async suggestTool(prompt: string) : Promise<Result<RoutingSuggestion, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suggest_tool", { prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dispatch a task to the specified tool (claude or gemini).
 */
async dispatchTask(prompt: string, projectDir: string, toolName: string, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_task", { prompt, projectDir, toolName, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Preview optimized prompts for all supported tools without dispatching.
 */
async optimizePrompt(prompt: string, projectDir: string) : Promise<Result<OptimizedPrompt[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("optimize_prompt", { prompt, projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type OutputEvent = { event: "stdout"; data: string } | { event: "stderr"; data: string } | { event: "exit"; data: number } | { event: "error"; data: string }
export interface RoutingSuggestion { suggested_tool: string; confidence: number; reason: string; alternative_tool: string | null; tool_available: boolean }
export interface WorktreeEntry { task_id: string; worktree_name: string; branch_name: string; path: string; created_at: string }
export interface ConflictFile { path: string }
export interface ConflictReport { has_conflicts: boolean; conflicting_files: ConflictFile[]; worktree_a: string; worktree_b: string }
export interface OptimizedPrompt { tool_name: string; original_prompt: string; optimized_prompt: string }
/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
