
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async startStream(onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_stream", { onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTaskCount() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async spawnProcess(cmd: string, args: string[], cwd: string, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_process", { cmd, args, cwd, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelProcess(taskId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_process", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseProcess(taskId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_process", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeProcess(taskId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_process", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns a list of currently running process task IDs.
 * Frontend uses this to reconcile its task state with backend reality.
 */
async getRunningProcesses() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_running_processes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn a Claude Code subprocess in headless streaming mode.
 * 
 * Retrieves the API key from the macOS Keychain, builds the Claude CLI command,
 * and spawns it through the process manager with secure env var injection.
 * The prompt is expected to be already optimized by the prompt engine (dispatch_task handles this).
 * 
 * Returns the task_id for tracking the process.
 */
async spawnClaudeTask(prompt: string, projectDir: string, taskId: string | null, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_claude_task", { prompt, projectDir, taskId, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Store a Claude API key in the macOS Keychain.
 * 
 * Validates that the key starts with "sk-ant-" before storing.
 * SECURITY: The key is never logged or included in error messages.
 */
async setClaudeApiKey(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_claude_api_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether a Claude API key is stored in the macOS Keychain.
 */
async hasClaudeApiKey() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_claude_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate a Claude Code result JSON for silent failures.
 * 
 * Parses the result JSON line with `parse_stream_line`, then validates via
 * `validate_result` — checking is_error, empty result, zero turns, and status.
 */
async validateClaudeResult(resultJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_claude_result", { resultJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the stored Claude API key from the macOS Keychain.
 */
async deleteClaudeApiKey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_claude_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record a task completion event with file changes.
 */
async recordTaskCompletionCmd(taskId: string, toolName: string, eventType: string, prompt: string | null, summary: string | null, projectDir: string, durationMs: number | null, costUsd: number | null, filesJson: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_task_completion_cmd", { taskId, toolName, eventType, prompt, summary, projectDir, durationMs, costUsd, filesJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get recent file changes for a project.
 */
async getRecentChanges(projectDir: string, limit: number) : Promise<Result<FileChangeRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recent_changes", { projectDir, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a summary of recent context events with their file paths.
 */
async getContextSummary(projectDir: string, limit: number) : Promise<Result<ContextEventWithFiles[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_context_summary", { projectDir, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create an isolated git worktree for a task.
 * 
 * Creates a new branch and worktree directory in a sibling `.whalecode-worktrees/` folder.
 * Returns the WorktreeEntry for frontend tracking.
 */
async createWorktree(taskId: string, projectDir: string) : Promise<Result<WorktreeEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_worktree", { taskId, projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check for file-level conflicts between two worktree branches.
 * 
 * Auto-commits any uncommitted changes in both worktrees before running
 * the three-way merge conflict detection.
 */
async checkWorktreeConflicts(projectDir: string, branchA: string, branchB: string) : Promise<Result<ConflictReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_worktree_conflicts", { projectDir, branchA, branchB }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate per-file unified diffs between a worktree branch and the default branch.
 * 
 * Auto-commits any uncommitted changes in the worktree before generating diffs
 * to capture all tool changes.
 */
async getWorktreeDiff(projectDir: string, branchName: string) : Promise<Result<WorktreeDiffReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_worktree_diff", { projectDir, branchName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Merge a worktree branch into the main/default branch.
 * 
 * SAFE-04: Pre-merge conflict gate — checks for conflicts against the default branch
 * and all other active whalecode branches before merging. If any conflicts are detected,
 * the merge is blocked and an error is returned.
 */
async mergeWorktree(projectDir: string, branchName: string, acceptedFiles: string[] | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_worktree", { projectDir, branchName, acceptedFiles }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clean up stale/invalid worktrees from previous crashed sessions.
 * 
 * Returns the names of worktrees that were cleaned up.
 */
async cleanupWorktrees(projectDir: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_worktrees", { projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all active whalecode worktrees for the project.
 */
async listWorktrees(projectDir: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_worktrees", { projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeSingleWorktree(projectDir: string, branchName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_single_worktree", { projectDir, branchName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn a Gemini CLI subprocess in headless streaming mode.
 * 
 * Retrieves the API key from the macOS Keychain, builds the Gemini CLI command,
 * and spawns it through the process manager with secure env var injection.
 * The prompt is expected to be already optimized by the prompt engine (dispatch_task handles this).
 * 
 * Returns the task_id for tracking the process.
 */
async spawnGeminiTask(prompt: string, projectDir: string, taskId: string | null, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_gemini_task", { prompt, projectDir, taskId, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Store a Gemini API key in the macOS Keychain.
 * 
 * Validates that the key is non-empty and has reasonable length (> 10 chars).
 * NOTE: Gemini API keys have no known prefix pattern (unlike Claude's sk-ant-).
 * SECURITY: The key is never logged or included in error messages.
 */
async setGeminiApiKey(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_gemini_api_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether a Gemini API key is stored in the macOS Keychain.
 */
async hasGeminiApiKey() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_gemini_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate a Gemini CLI result JSON for silent failures.
 * 
 * Parses the result JSON line with `parse_stream_line`, then validates via
 * `validate_result` — checking empty response, error status, and error events.
 */
async validateGeminiResult(resultJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_gemini_result", { resultJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the stored Gemini API key from the macOS Keychain.
 */
async deleteGeminiApiKey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_gemini_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn a Codex CLI subprocess in headless streaming mode.
 * 
 * Retrieves the API key from the macOS Keychain, builds the Codex CLI command,
 * and spawns it through the process manager with secure env var injection.
 * The prompt is expected to be already optimized by the prompt engine (dispatch_task handles this).
 * 
 * Returns the task_id for tracking the process.
 */
async spawnCodexTask(prompt: string, projectDir: string, taskId: string | null, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_codex_task", { prompt, projectDir, taskId, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Store a Codex (OpenAI) API key in the macOS Keychain.
 * 
 * Validates that the key starts with "sk-" (OpenAI key format) and is non-empty.
 * SECURITY: The key is never logged or included in error messages.
 */
async setCodexApiKey(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_codex_api_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether a Codex (OpenAI) API key is stored in the macOS Keychain.
 */
async hasCodexApiKey() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_codex_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate a Codex CLI result JSON for silent failures.
 * 
 * Parses the result JSON line with `parse_stream_line`, then validates via
 * `validate_result` — checking empty response, error status, and error events.
 */
async validateCodexResult(resultJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_codex_result", { resultJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the stored Codex (OpenAI) API key from the macOS Keychain.
 */
async deleteCodexApiKey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_codex_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Suggest the best tool for a given prompt based on keyword heuristics and tool availability.
 * 
 * Checks which tools currently have running processes to determine busyness,
 * then delegates to TaskRouter::suggest for the routing decision.
 */
async suggestTool(prompt: string) : Promise<Result<RoutingSuggestion, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suggest_tool", { prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dispatch a task to the specified tool (claude or gemini).
 * 
 * Enforces max 1 running process per tool. Routes to the correct spawn function
 * based on tool_name, then updates the ProcessEntry with tool metadata.
 * 
 * Uses an atomic reservation pattern to prevent TOCTOU races: the tool is reserved
 * in the same lock scope as the running-process check, and a RAII guard ensures
 * the reservation is always released (even on early error returns).
 */
async dispatchTask(prompt: string, projectDir: string, toolName: string, taskId: string | null, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_task", { prompt, projectDir, toolName, taskId, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dispatch an orchestrated multi-agent task using interactive master process.
 * 
 * Phase 1 (Decompose): Master agent spawned in interactive mode, receives
 * decompose prompt, returns JSON sub-task assignments.
 * Phase 2 (Execute): Each sub-task dispatched to assigned agent. Worker
 * questions are routed to the master for resolution.
 * Phase 3 (Review): Master (same process) reviews all worker results.
 * Master stays alive after completion for follow-up interactions.
 */
async dispatchOrchestratedTask(prompt: string, projectDir: string, config: OrchestratorConfig, onEvent: TAURI_CHANNEL<OutputEvent>) : Promise<Result<OrchestrationPlan, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_orchestrated_task", { prompt, projectDir, config, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get context/token usage information for agents involved in a task.
 */
async getAgentContextInfo(taskId: string) : Promise<Result<AgentContextInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent_context_info", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Preview optimized prompts for all supported tools without dispatching.
 * 
 * Returns a Vec<OptimizedPrompt> showing how the prompt would be transformed
 * for each tool (claude, gemini). Used by frontend for prompt preview UI.
 */
async optimizePrompt(prompt: string, projectDir: string) : Promise<Result<OptimizedPrompt[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("optimize_prompt", { prompt, projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send text to a running process's stdin.
 */
async sendToProcess(taskId: string, text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_to_process", { taskId, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove completed/failed processes older than 30 seconds from state.
 */
async cleanupCompletedProcesses() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_completed_processes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear orchestration context: back up master's context to context.md,
 * kill all agent processes, and remove the plan.
 */
async clearOrchestrationContext(planId: string, projectDir: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_orchestration_context", { planId, projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Answer a question from the master agent that was relayed to the user.
 * Sends the user's answer to the master's stdin and resumes execution.
 */
async answerUserQuestion(planId: string, answer: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("answer_user_question", { planId, answer }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Approve the decomposed task list (optionally modified) and start execution.
 */
async approveDecomposition(planId: string, modifiedTasks: SubTaskDef[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_decomposition", { planId, modifiedTasks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reject the decomposition and send feedback to the master for re-decomposition.
 */
async rejectDecomposition(planId: string, feedback: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reject_decomposition", { planId, feedback }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Approve the decomposed task list and start Phase 2 execution.
 * Optionally accepts modified tasks (agent reassignments, removals).
 */
async approveOrchestration(planId: string, modifiedTasks: SubTaskDef[] | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_orchestration", { planId, modifiedTasks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectAgents() : Promise<Result<DetectedAgent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_agents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchAgentUsage() : Promise<Result<AgentUsage[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_agent_usage") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitStatus(projectDir: string) : Promise<Result<GitStatusReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_status", { projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitStageFiles(projectDir: string, paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_stage_files", { projectDir, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitUnstageFiles(projectDir: string, paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_unstage_files", { projectDir, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitCommit(projectDir: string, message: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_commit", { projectDir, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitDiffFile(projectDir: string, filePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_diff_file", { projectDir, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitLog(projectDir: string, limit: number) : Promise<Result<GitLogEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_log", { projectDir, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitPull(projectDir: string) : Promise<Result<GitPullResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_pull", { projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitPush(projectDir: string) : Promise<Result<GitPushResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_push", { projectDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDirectory(projectDir: string, relativePath: string) : Promise<Result<FsEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_directory", { projectDir, relativePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFile(projectDir: string, relativePath: string) : Promise<Result<FileContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { projectDir, relativePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeFile(projectDir: string, relativePath: string, content: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_file", { projectDir, relativePath, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConfig() : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setConfig(config: AppConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get orchestration history records.
 */
async getOrchestrationHistory(limit: number) : Promise<Result<OrchestrationRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_orchestration_history", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentConfig = { tool_name: string; sub_agent_count: number; is_master: boolean }
export type AgentContextInfo = { tool_name: string; input_tokens: number | null; output_tokens: number | null; total_tokens: number | null; cost_usd: number | null; status: string }
export type AgentUsage = { agent: string; plan: string | null; lines: UsageLine[]; error: string | null }
/**
 * App configuration with sensible defaults.
 * Stored as `whalecode.json` in the app data directory.
 */
export type AppConfig = { 
/**
 * Master agent timeout in minutes (default: 10)
 */
master_timeout_minutes: number; 
/**
 * Worker agent timeout in minutes (default: 5)
 */
worker_timeout_minutes: number; 
/**
 * Maximum rate limit retries before failing (default: 3)
 */
max_rate_limit_retries: number; 
/**
 * Maximum worker retries before marking as failed (default: 2)
 */
max_worker_retries: number; 
/**
 * Seconds to wait before cleaning up completed plans (default: 60)
 */
plan_cleanup_delay_secs: number; 
/**
 * Maximum concurrent workers (default: 3)
 */
max_concurrent_workers: number }
export type AuthStatus = "Authenticated" | "NeedsAuth" | "NotInstalled" | "Unknown"
export type ConflictFile = { path: string }
export type ConflictReport = { has_conflicts: boolean; conflicting_files: ConflictFile[]; worktree_a: string; worktree_b: string }
/**
 * A context event with its associated file paths, suitable for IPC return.
 */
export type ContextEventWithFiles = { id: number; task_id: string; tool_name: string; event_type: string; prompt: string | null; summary: string | null; project_dir: string; metadata: string | null; duration_ms: number | null; cost_usd: number | null; created_at: string; files: string[] }
export type DecompositionResult = { tasks: SubTaskDef[] }
export type DetectedAgent = { tool_name: string; installed: boolean; binary_path: string | null; version: string | null; auth_status: AuthStatus; display_name: string }
export type FileChangeRecord = { file_path: string; change_type: string; tool_name: string; summary: string | null; created_at: string }
export type FileContent = { content: string; truncated: boolean; size: number; language: string }
export type FileDiff = { path: string; status: string; old_path: string | null; patch: string; additions: number; deletions: number }
export type FsEntry = { name: string; path: string; is_dir: boolean; size: number; extension: string }
export type GitFileEntry = { path: string; status: string; additions: number; deletions: number }
export type GitLogEntry = { hash: string; message: string; author: string; time_ago: string }
export type GitPullResult = { success: boolean; message: string }
export type GitPushResult = { success: boolean; message: string }
export type GitStatusReport = { branch: string; ahead: number; behind: number; staged: GitFileEntry[]; unstaged: GitFileEntry[]; untracked: string[] }
/**
 * An optimized prompt for a specific tool, ready for IPC export.
 */
export type OptimizedPrompt = { tool_name: string; original_prompt: string; optimized_prompt: string }
export type OrchestrationPhase = "Decomposing" | "AwaitingApproval" | "Executing" | "WaitingForInput" | "Reviewing" | "Completed" | "Failed"
export type OrchestrationPlan = { task_id: string; original_prompt: string; sub_tasks: SubTask[]; master_agent: string; phase: OrchestrationPhase; decomposition: DecompositionResult | null; worker_results: WorkerResult[]; master_process_id: string | null }
export type OrchestrationRecord = { id: number; task_id: string; agent_count: number; duration_secs: number; success: boolean; created_at: string }
export type OrchestratorConfig = { agents: AgentConfig[]; master_agent: string }
export type OutputEvent = { event: "stdout"; data: string } | { event: "stderr"; data: string } | { event: "exit"; data: number } | { event: "error"; data: string }
export type RoutingSuggestion = { suggested_tool: string; confidence: number; reason: string; alternative_tool: string | null; tool_available: boolean }
export type SubTask = { id: string; prompt: string; assigned_agent: string; status: string; parent_task_id: string; depends_on?: string[] }
export type SubTaskDef = { id?: string | null; agent: string; prompt: string; description: string; depends_on?: string[] }
export type TAURI_CHANNEL<TSend> = TAURI_CHANNEL_IMPORT<TSend>
export type UsageLine = { line_type: string; label: string; value: string | null; used: number | null; limit: number | null; format_kind: string | null; resets_at: string | null }
export type WorkerResult = { task_id: string; agent: string; exit_code: number; output_summary: string; retry_count?: number; original_agent?: string | null; failure_reason?: string | null }
export type WorktreeDiffReport = { branch_name: string; default_branch: string; files: FileDiff[]; total_additions: number; total_deletions: number }
export type WorktreeEntry = { task_id: string; worktree_name: string; branch_name: string; path: string; 
/**
 * ISO 8601 timestamp string (specta does not implement Type for chrono::DateTime)
 */
created_at: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL_IMPORT,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

// @ts-ignore — auto-generated by tauri-specta
function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
